### ISSUE TITLE
Kiali install requires envsubst

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/istio-tutorial#122]
A note should be added to the Kiali doc 
https://github.com/redhat-developer-demos/istio-tutorial/blob/master/documentation/modules/advanced/pages/kiali.adoc
that envsubst is a required command line tool and it can be installed on Mac
brew install gettext
brew link --force gettext 
we need to find the Linux install option as well and also work on a Windows option (Windows bash at least)

**Comment by lordofthejars** [comment]
it has been added in https://github.com/redhat-developer-demos/istio-tutorial/pull/124
