### ISSUE TITLE
cd ~/ springboot - istio-tutorial - error cmd [Scenario 2][Deploy microservices]

### ISSUE THREAD

**Issue by svlaskovic** [redhat-developer-demos/istio-tutorial#130]
https://learn.openshift.com/servicemesh

cd ~/projects/istio-tutorial/preference/java/springboot
-bash: cd: /root/projects/istio-tutorial/preference/java/springboot: No such file or directory

Step 4 of 5: Deploy Preference microservice

Thank you,
Slobodanka

**Comment by rafabene** [comment]
I couldn't reproduce. Can you please, try again and reopen this issue if the problem still persists?
