### ISSUE TITLE
Using Maistra to install Istio

### ISSUE THREAD

**Issue by kameshsampath** [redhat-developer-demos/istio-tutorial#143]
It will be nice to have Istio installed using[ Maistra.io ](http://maistra.io/)

**Comment by tvieira** [comment]
Hi @kameshsampath, please feel free to assign it to me and I can send a PR before the end of today.

**Comment by kameshsampath** [comment]
thanks @tvieira ,  will review and merge once I see it int. thanks for the support

**Comment by lordofthejars** [comment]
Just one thing please do not remove any existing part but added as a new section so we still have both approaches ready.

**Comment by kameshsampath** [comment]
i would feel we have both

**Comment by tvieira** [comment]
I don't like the idea of having two options. RHOSM adds two more components in the bundle, Jaeger and Kiali (and Kiali will become the default in upstream soon), and all the permissions are set automatically. I think if someone thinks that RHOSM is not Istio, this is an issue in the communication channels.

Even though, I'm adding the two options for now. Please let me know what do you think.

**Comment by lordofthejars** [comment]
This tutorial is not meant to be consumed only by OpenShift users but also for K8s ones.

**Comment by tvieira** [comment]
@lordofthejars that would make more sense if the tutorial uses minikube instead of minishift.

**Comment by lordofthejars** [comment]
And it is going to happen Burr has the script prepared.
