### ISSUE TITLE
Implements RBAC section

### ISSUE THREAD

**Issue by lordofthejars** [redhat-developer-demos/istio-tutorial#144]

**Comment by rafabene** [comment]
Although I've merged RBAC section, can you take a look at "Authorization and JWT"?

My output for  curl -H "Authorization: Bearer $token" customer-tutorial.$(minishift ip).nip.io is RBAC: access denied

My token is: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI0NUpUeG9ZZ0lNenVkYzRFeVVkOHFGWlVpOVZTcU8zVXdhVVBQdy1nXzRBIn0.eyJqdGkiOiI2MzFhMWM5Yi02ZjYwLTRjNjQtYmYxNi00NDllM2VlNTBjNjEiLCJleHAiOjE1NDE3ODAyNTgsIm5iZiI6MCwiaWF0IjoxNTQxNzc5OTU4LCJpc3MiOiJodHRwOi8va2V5Y2xvYWstdHV0b3JpYWwuMTkyLjE2OC42NC4xMy5uaXAuaW8vYXV0aC9yZWFsbXMvaXN0aW8iLCJhdWQiOiJjdXN0b21lci10dXRvcmlhbCIsInN1YiI6Ijc1NzQwNmNkLWY5NGEtNDdmNS04YjIwLTI1ODEzMTNhMjU2ZCIsInR5cCI6IkJlYXJlciIsImF6cCI6ImN1c3RvbWVyLXR1dG9yaWFsIiwiYXV0aF90aW1lIjowLCJzZXNzaW9uX3N0YXRlIjoiZWRmYjgyMTgtYTU4ZC00ODk4LTk5OWItMWU1ZTE2NWNjZGQwIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6W10sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIiwidXNlciJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoiZGVtbyJ9.g44mJGkAgZZjsZChegqhaww8hcOBE3Nvs9QWrjUqsgUHpa1kwsYpj3MvPlozTjz0NZxZE_QQJYRJuJWWLh-6NPkSUFrHnH-hVA1fJp9RaeKnRYEU8IbqN5DPEDuMtH4guV2K_suk3PAd9chUbVr4lZ1TmmerOIR0_Ho14zjrBnBnjx0qpuS9MzhLy5kpBYF-BS19w6tjUqBNz_TDuwWZbkIjshcBRb8dg--0PA6bs0A8e-NXMSI5MkYlMdnjCJ04hyey4UPUUlcPhBM2XpBAzjZpwjKCq1u0sBybtz3UnbBB4nz0zFPmqkqAoHLn4wWmwLpXCcSRurkVYj8gZChJsw

**Comment by lordofthejars** [comment]
Well I'll check, I run it two weeks ago and it worked. Maybe the problem
with the import script? Have you tried running with new keycloak instance
and doing all manual steps? It might be a problem with iss field
