### ISSUE TITLE
jaeger core propagates b3 headers for traces

### ISSUE THREAD

**Issue by cmoulliard** [redhat-developer-demos/istio-tutorial#15]
jaeger core propagates b3 headers for traces

FYI : https://issues.jboss.org/browse/SB-424?focusedCommentId=13513905&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13513905

With environment variable (JAEGER_PROPAGATION = b3), as shown in this template: https://github.com/objectiser/opentracing-prometheus-example/blob/master/simple/services-istio-kubernetes.yml#L37 (this example shows a spring-boot app deployed to Istio where the app also participates in the trace - see ordermgr).

**Comment by rafabene** [comment]
@cmoulliard Can you send a PR?

**Comment by rafabene** [comment]
Handled in #57
