### ISSUE TITLE
no istioctl when installing with operator

### ISSUE THREAD

**Issue by hupiper** [redhat-developer-demos/istio-tutorial#150]
When you use the operator to install istio, istioctl is not created nor put in your path, so the instructions in 2deploy-microservices.adoc do not work if you followed the new path for install.

**Comment by rafabene** [comment]
That's why you should run the commands:

pushd istio-1.0.2
export ISTIO_HOME=`pwd`
export PATH=$ISTIO_HOME/bin:$PATH
popd

as the specified in the document.

**Comment by hupiper** [comment]
istioctl is never installed - that's my point. You can't add it to your path if you never install it.

**Comment by hupiper** [comment]
Close it if you like, but you didn't address it.

**Comment by hupiper** [comment]
I've actually made this comment in two places.  The first one you skip installing istioctl when using the operator install - you should tell people that you need to install istioctl with either method. Be specific.

The second comment is in the service mesh install instructions where you don't install istioctl at all, and your cleanup script will not work without it.  I'm just trying to help you make the docs  better.

**Comment by rafabene** [comment]
The installation using operator has been removed. We are using only the upstream.
