### ISSUE TITLE
there no traces service,what's the problem

### ISSUE THREAD

**Issue by damozhiying** [redhat-developer-demos/istio-tutorial#157]
when i run customer → preference → recommendation  service  local and 

docker run -d \
  --rm \
  -p5775:5775/udp \
  -p6831:6831/udp \
  -p6832:6832/udp \
  -p16686:16686 \
  -p14268:14268 \
  jaegertracing/all-in-one:1.3

![image](https://user-images.githubusercontent.com/10277950/48105753-adcfe700-e273-11e8-9588-5e571bce5815.png)
there no traces service

**Comment by rafabene** [comment]
It will only provide traces if you run jaeger inside the kubernetes/Openshift cluster. Otherwise, microservices can't locate this containers outside the cluster.
