### ISSUE TITLE
Katacoda Impact: HTTP Error makes Katacoda scenario to not display the application or error log

### ISSUE THREAD

**Issue by rafabene** [redhat-developer-demos/istio-tutorial#16]
When the exception is propagated to Customer, it impacts Katacoda as any HTTP response that is not 20x will cause Katacoda to say that the application is not available, thus the steps https://github.com/redhat-developer-demos/istio-tutorial#deploy-customer and https://github.com/redhat-developer-demos/istio-tutorial#deploy-preferences will fail. You can check this behaviour by running the Katacoda scenario https://www.katacoda.com/rafabene/courses/workshop/2-deploy-microservices

**Comment by rafabene** [comment]
The Step https://github.com/redhat-developer-demos/istio-tutorial#http-error-503 also fails. You can check it running the Scenario https://www.katacoda.com/rafabene/courses/workshop/5-fault-injection

**Comment by BenHall** [comment]
We're looking at changing this. For certain requests we want to have this behaviour (Openshift dashboard still loading), where as application errors we want to show the error.

**Comment by burrsutter** [comment]
We need the HTTP error code to be returned from the app as that is what Istio seems to be monitoring for things like circuit-breakers.

**Comment by kameshsampath** [comment]
yes for Istio circuit breakers to work we need right error codes - in this case HTTP 5xx

**Comment by BenHall** [comment]
We can change that

**Comment by rafabene** [comment]
@BenHall Giving this discussion and how Istio handles circuit breakers, we need to change that. What's the procedure? Should I report that somewhere?

**Comment by rafabene** [comment]
@BenHall Do you have any updates on this? Thank you

**Comment by rafabene** [comment]
Solved in Katacoda. Reference: https://trello.com/c/AjTJfVNc/48-application-error-avoids-katacoda-to-show-its-message
