### ISSUE TITLE
https://github.com/redhat-developer-demos/istio-tutorial/wiki/Istio-Installation  not valid for 0.8+ istio

### ISSUE THREAD

**Issue by jerzy-wachowiak** [redhat-developer-demos/istio-tutorial#162]
redhat-developer-demos/istio-tutorial is valid up to istio 0.6 
Ther are not addons in the istio distribution any more

**Comment by rafabene** [comment]
How do you mean. Istio-tutorial uses 1.0.x. Why do you say that is not valid?

**Comment by jerzy-wachowiak** [comment]
Please see https://github.com/redhat-developer-demos/istio-tutorial/wiki/Istio-Installation and compare with the content of e.g. https://github.com/istio/istio/releases/download/1.0.3/istio-1.0.3-win.zip
1) addons directory is empty but the wiki page says
oc apply -f install/kubernetes/addons/prometheus.yaml
oc apply -f install/kubernetes/addons/grafana.yaml
oc apply -f install/kubernetes/addons/servicegraph.yaml
what results in error
2) there is no more istio.yaml but istio-demo.yaml, etc.

**Comment by lordofthejars** [comment]
Don't use wiki, use https://redhat-developer-demos.github.io/istio-tutorial/istio-tutorial/1.0.0/1setup.html

@rafabene Maybe we should remove all wiki parts

**Comment by rafabene** [comment]
Removed and closed.
