### ISSUE TITLE
/etc/sysctl.d/99-elasticsearch.conf disappears after minishift stop & start

### ISSUE THREAD

**Issue by jerzy-wachowiak** [redhat-developer-demos/istio-tutorial#163]
**Setup**
Win 10 / Virtual Box / openshift v3.11.0+6c2b013-59) / minishift v1.26.1+1e20f27

**Reffers to**
(Option 1) Red Hat OpenShift Service Mesh installation → script setting the system limits on mmap counts
```
$ minishift ssh
[docker@istio-tutorial ~]$ sudo -i
[root@istio-tutorial ~]$ echo "vm.max_map_count = 262144" > /etc/sysctl.d/99-elasticsearch.conf
[root@istio-tutorial ~]$ sysctl vm.max_map_count=262144
[root@istio-tutorial ~]$ exit
logout
[docker@istio-tutorial ~]$ exit
logout
```

**Issue**
/etc/sysctl.d/99-elasticsearch.conf disappears after minishift stop and start 

**Investigation**
It seems, that on Minishift start some parts of /etc are overwritten. This behavior could not be observed for minishift openshift restart
Directories before the script setting the system limits on mmap counts
```
drwxr-xr-x.  82 root root  4096 Nov 19 08:30 etc
drwxr-xr-x.  2 root root   4096 Oct 23 11:45 sysctl.d
-rw-r--r--.  1 root root    449 Sep 26 18:25 sysctl.conf
```

```
[root@minishift-virtualbox-default sysctl.d]# echo "vm.max_map_count = 262144" > /etc/sysctl.d/99-elasticsearch.conf
[root@minishift-virtualbox-default sysctl.d]# ls -l
-rw-r--r--. 1 root root 26 Nov 19 08:40 99-elasticsearch.conf
lrwxrwxrwx. 1 root root 14 Oct 23 11:45 99-sysctl.conf -> ../sysctl.conf
```

minishift stop and start 
```
drwxr-xr-x.  82 root root  4096 Nov 19 08:47 etc
-rw-r--r--.  1 root root    449 Sep 26 18:25 sysctl.conf
drwxr-xr-x.  2 root root   4096 Oct 23 11:45 sysctl.d

[root@minishift-virtualbox-default sysctl.d]# ls -l
lrwxrwxrwx. 1 root root 14 Oct 23 11:45 99-sysctl.conf -> ../sysctl.conf

[root@minishift-virtualbox-default ~]# dmsetup status live-rw
0 20971520 snapshot 342128/1048576 1344

[root@minishift-virtualbox-default /]# df /etc/sysctl.d
Filesystem          1K-blocks   Used Available Use% Mounted on /dev/mapper/live-rw  10190100 718584   9350324   8% /
```

**Workaround** 
To setup manually after each minishift start
```
minishift ssh -- 'sudo sysctl -w vm.max_map_count=262144'
```

**Comment by jerzy-wachowiak** [comment]
It seems to be a problem on Minishift as the way over /var/lib/boot2docker/bootlocal.sh doesn't exist
https://github.com/jaegertracing/jaeger-openshift/issues/51

**Comment by reneklootwijk** [comment]
+1

**Comment by rafabene** [comment]
So it seems that this is a issue related to minishift, not this tutorial, so I'm closing it.

Thank you @jerzy-wachowiak for the research.
