### ISSUE TITLE
IMPORTANT: When updating to Istio 1.1.0

### ISSUE THREAD

**Issue by lordofthejars** [redhat-developer-demos/istio-tutorial#165]
When updating the tutorial to Istio 1.1.0 it is important that just before merging the change, we create a tag on documentation to version 1.0.0 (removing the existing one and create a new one) and pushing upstream. In this way we will be able to maintain several versions of Istio working on our tutorial.

Then I'll take care of modifying Antora to adapt to this change.

**Comment by rafabene** [comment]
I think this can be closed, right @lordofthejars ?

**Comment by lordofthejars** [comment]
Well, actually it is a reminder for when we migrate the tutorial to Istio 1.1.0 to create a tag for 1.0.0 at that time.

**Comment by rafabene** [comment]
Tag created: https://github.com/redhat-developer-demos/istio-tutorial/releases/tag/1.0.x
