### ISSUE TITLE
Missing S2I deployment description in https://redhat-developer-demos.github.io/istio-tutorial/istio-tutorial/1.0.0/6fault-injection.html#timeout

### ISSUE THREAD

**Issue by jerzy-wachowiak** [redhat-developer-demos/istio-tutorial#171]
**Setup**
Win 10 / VirtualBox / openshift v3.11.0+6c2b013-59) / minishift v1.26.1+1e20f27

**Referce to**
https://redhat-developer-demos.github.io/istio-tutorial/istio-tutorial/1.0.0/6fault-injection.html#timeout

**Issue**
No institutions for deployment according to the S2I Strategy provided, only docker way described

**Solution**
Something like
```
cd /c/tmp/istio-tutorial
mvn clean package -f recommendation/java/vertx
oc start-build recommendation-v2 --from-dir=. --follow -n tutorial
oc get pods -l app=recommendation -n tutorial
```

**Comment by rafabene** [comment]
We will be removing the S2i option from this tutorial. See #199
