### ISSUE TITLE
SpringBoot recommendation doesn't produce log

### ISSUE THREAD

**Issue by rafabene** [redhat-developer-demos/istio-tutorial#188]
The SpringBoot version doesn't produce request logs so it makes hard to show Dark Launches, thus it should also be fixed

**Comment by kameshsampath** [comment]
I have deleted the SB recommendation and pushed back v1 and v2 of vertx recommendation. 

`docker pull quay.io/rhdevelopers/istio-tutorial-recommendation:v1`
`docker pull quay.io/rhdevelopers/istio-tutorial-recommendation:v2`

@rafabene  please test and let me know.

**Comment by rafabene** [comment]
It is working perfectly! Thank you!
