### ISSUE TITLE
Springboot recommendation is only failing once.

### ISSUE THREAD

**Issue by rafabene** [redhat-developer-demos/istio-tutorial#189]
The lines bellow are impacting the Service Resilience scenarios because it fails just once and then it "resets" itself to be fixed again with count=0

https://github.com/redhat-developer-demos/istio-tutorial/blob/85c26a8609a32a437d4520885bb5ca287b77a135/recommendation/java/springboot/src/main/java/com/redhat/developer/demos/recommendation/RecommendationController.java#L57-L58

**Comment by kameshsampath** [comment]
@rafabene  i cant come back to this until i am done with Knative tutorial, would mind sending a PR ?

**Comment by rafabene** [comment]
Sure! But I will finish the workshop documentation first
