### ISSUE TITLE
Images on Kiali page are not linked

### ISSUE THREAD

**Issue by mtho11** [redhat-developer-demos/istio-tutorial#192]
On the Kiali page:
 https://github.com/redhat-developer-demos/istio-tutorial/blob/master/documentation/modules/advanced/pages/kiali.adoc

All of the images links are broken -->

![image](https://user-images.githubusercontent.com/1312165/53767390-85a36e00-3e8a-11e9-842f-5af764479922.png)

**Comment by rafabene** [comment]
It is meant to be seen in a HTML page generated by Antora: https://redhat-developer-demos.github.io/istio-tutorial/istio-tutorial/1.0.x/advanced/kiali.html#applications

We really expect that it won't be seen via Github:
