### ISSUE TITLE
update the kiali install instructions - no need to git clone src repo

### ISSUE THREAD

**Issue by jmazzitelli** [redhat-developer-demos/istio-tutorial#193]
looking here:
https://github.com/redhat-developer-demos/istio-tutorial/blob/master/documentation/modules/advanced/pages/kiali.adoc#how-to-install-kiali

the Kiali install instructions are a bit heavy. There is no need to ask the user to git clone the kiali source repository. See https://www.kiali.io/gettingstarted/#_install_kiali for the true install instructions. In short:

`bash <(curl -L http://git.io/getLatestKiali)`

should be what you need. If you want to get the jaeger and grafana URLs it would be:

```
export JAEGER_URL="http://tracing-istio-system.$(minishift ip).nip.io"
export GRAFANA_URL="http://grafana-istio-system.$(minishift ip).nip.io"
bash <(curl -L http://git.io/getLatestKiali)
```

**Comment by mtho11** [comment]
Summary of Kiali install options:
https://www.kiali.io/documentation/installation/

**Comment by rafabene** [comment]
Kiali is installed as part of Istio 1.1 - So no installation is needed anymore.

Fixed at https://github.com/redhat-developer-demos/istio-tutorial/commit/01e9e5e1aa094161fa1ad09595cf4d36b30073d6
