### ISSUE TITLE
documentation flow: 4simple-routerules.adoc

### ISSUE THREAD

**Issue by welshstew** [redhat-developer-demos/istio-tutorial#198]
istio-tutorial/documentation/modules/ROOT/pages/4simple-routerules.adoc

Surely in the below we are building from GitHub source, so the code change
`private static final String RESPONSE_STRING_FORMAT = "recommendation v2 from '%s': %d\n";` will
not be reflected.  Maybe add a note for the developer to fork and push, or just be aware that they're not building the change into the code from `https://github.com/redhat-developer-demos/istio-tutorial`

> === OpenShift S2I strategy (if you DON'T have access to Docker daemon)
> 
> [source, bash]
> ----
> mvn clean package -f recommendation/java/vertx
> oc new-app -l app=recommendation,version=v2 --name=recommendation-v2 --context-dir=recommendation/java/vertx -e JAEGER_SERVICE_NAME=recommendation JAEGER_ENDPOINT=http://jaeger-collector.istio-system.svc:14268/api/traces JAEGER_PROPAGATION=b3 JAEGER_SAMPLER_TYPE=const JAEGER_SAMPLER_PARAM=1 JAVA_OPTIONS='-Xms128m -Xmx256m -Djava.net.preferIPv4Stack=true' fabric8/s2i-java~https://github.com/redhat-developer-demos/istio-tutorial -o yaml  > recommendation-v2.yml
> oc apply -f <(istioctl kube-inject -f recommendation-v2.yml) -n tutorial
> oc cancel-build bc/recommendation-v2 -n tutorial
> oc delete svc/recommendation-v2 -n tutorial
> oc start-build recommendation-v2 --from-dir=. --follow -n tutorial
> ----

**Comment by rafabene** [comment]
s2i option has been removed by #199
