### ISSUE TITLE
http://now.httpbin.org/ has been removed. Egress is not working anymore.

### ISSUE THREAD

**Issue by rafabene** [redhat-developer-demos/istio-tutorial#203]
We need to provide an alternative

**Comment by lordofthejars** [comment]
I have one, tomorrow I ll update the issue with the service I am using now

**Comment by lordofthejars** [comment]
http://worldclockapi.com/api/json/cet/now

**Comment by lordofthejars** [comment]
I'll try to send a PR today fixing it

**Comment by lordofthejars** [comment]
@rafabene Working on that now

**Comment by rafabene** [comment]
Thanks @lordofthejars

**Comment by rafabene** [comment]
@lordofthejars Note that the default implementation will become quarkus as defined at #202 and #201

**Comment by lordofthejars** [comment]
But for now quarkus does not have any logic regarding this, so I should implement from 0 right?

**Comment by lordofthejars** [comment]
@rafabene https://github.com/redhat-developer-demos/istio-tutorial/pull/206
