### ISSUE TITLE
Quarkus needs to set baggage header to have Canary using user agent working

### ISSUE THREAD

**Issue by rafabene** [redhat-developer-demos/istio-tutorial#205]
Quarkus doesn't set the user agent at the baggage thus Canary deployment based on the user agent is not working.

Spring boot implementation for reference: https://github.com/redhat-developer-demos/istio-tutorial/blob/master/customer/java/springboot/src/main/java/com/redhat/developer/demos/customer/CustomerController.java#L55-L61

**Comment by rafabene** [comment]
Quarkus needs also to propagate the header to preference and recommendation.

**Comment by yanaga** [comment]
Tried to use the micro profile feature of header forwarding, which makes the code extremely simple: https://github.com/redhat-developer-demos/istio-tutorial/blob/11625d68bd7e734abcaf75a2a9ed6753f374a2cd/customer/java/quarkus/src/main/resources/application.properties#L1

The user-agent is propagated on both preference and recommendation. So yes, the behavior is different from the SB implementation, but makes the code super cleaner and straightforward. I prefer cleaner, but I can be outvoted on this one.

**Comment by yanaga** [comment]
Or else I can implement a ClientRequestFilter so we don't need to mess with the Quarkus code.

**Comment by lordofthejars** [comment]
That's fine the implementation that Edson showed, but shouldn't be `baggage-user.agent`? Check Istio files they are looking for this because of open tracing.

**Comment by yanaga** [comment]
I checked the microprofile implementation, and it's just forwarding the User-Agent like the Quarkus one. If I just want to forward the User-Agent is a matter of just declaring it in application.properties, but if I want to change it to another header I need to implement a ClientHeadersFactory - which is pretty straightforward too BTW. I'll change the implementation to have the same behavior as spring boot, but then we should remove the thorntail-based implementation, as it's not working anyway.

**Comment by lordofthejars** [comment]
well the `baggage` thing is added because of opentracing I guess not because of Spring Boot

**Comment by yanaga** [comment]
I know. I'm just complaining that the behavior is different between our implementations :-)

I fixed it already anyway. PR coming...

**Comment by yanaga** [comment]
PR #209 created.
