### ISSUE TITLE
Kiali installed by default in Istio 1.1.1

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/istio-tutorial#214]
In our doc we describe how to setup Kiali
https://redhat-developer-demos.github.io/istio-tutorial/istio-tutorial/1.1.x/3kiali.html#istioconf

But the service is in by default, just needs a Route or a NodePort

**Comment by rafabene** [comment]
The document shows how to update the default Kiali installation to see Jaeger and Grafana. Note that the informed object is a ConfigMap.
