### ISSUE TITLE
demonstrate quarkus metrics /metrics

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/istio-tutorial#215]
Add
> 
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-metrics</artifactId>
    </dependency>

which exposes /metrics

and figure out how to get those gathered into Prometheus automatically

**Comment by rafabene** [comment]
Mete did it before: https://meteatamel.wordpress.com/2019/01/07/application-metrics-in-istio/ It seems that we need to instrument the application

**Comment by rafabene** [comment]
Implemented in the commit: https://github.com/redhat-developer-demos/istio-tutorial/commit/005e2619c8038780f395c54d4684b3d806bb8bcb

**Comment by rafabene** [comment]
Documentation updated in this commit: https://github.com/redhat-developer-demos/istio-tutorial/commit/c866ef7315a62a209ed0159f36a5852f870fc53a
