### ISSUE TITLE
example/customer pod creation fails in step 2

### ISSUE THREAD

**Issue by jeremyrdavis** [redhat-developer-demos/istio-tutorial#217]
In step 2 the docker image does not deploy.  The following command 

`oc expose service customer -n tutorial`

produces:

`Error creating: pods "customer-65c7975fd4-" is forbidden: unable to validate against any security context constraint: [capabilities.add: Invalid value: "NET_ADMIN": capability may not be added capabilities.add: Invalid value: "NET_ADMIN": capability may not be added spec.containers[1].securityContext.securityContext.runAsUser: Invalid value: 1337: must be in the ranges: [1000180000, 1000189999]]`

**Comment by lordofthejars** [comment]
It seems a problem in the minishift configuration `minishift addon enable admin-user` and `minishift addon apply anyuid` and then log as admin `oc login $(minishift ip):8443 -u admin -p admin`
