### ISSUE TITLE
After stop/start VM minishift presents a oc login / project bug

### ISSUE THREAD

**Issue by lucasponce** [redhat-developer-demos/istio-tutorial#22]
Hi,
Just leave here some notes about something happened working with this tutorial.
I followed the initial instalation, and then I stopped minishift, after re-start it, it presented an issue reported here
https://github.com/minishift/minishift/issues/1966
In case this happened to other users or if it is some missing step from my side.

**Comment by rafabene** [comment]
Since this seems to be issue on https://github.com/minishift/minishift/, it seems that it doesn't make sense to have this issue opened here. I'm closing it. Please, reopen if you feel that it should be handled by this project.
