### ISSUE TITLE
CrashLoopBackOff error

### ISSUE THREAD

**Issue by ravichalla** [redhat-developer-demos/istio-tutorial#220]
oc get pods -w is giving:

pods with crashloopbackoff error.

**NAME                                                           READY     STATUS                    RESTARTS   AGE**
istio-egressgateway-88887488d-flhc9      0/1       CrashLoopBackOff       6               9m
istio-galley-787758f7b8-5x5pz                   0/1       CrashLoopBackOff       6               9m

**Comment by lordofthejars** [comment]
Are you running this:

minishift ssh -- sudo setenforce 0

# Openshift console bug. anyuid needs to be applied after startup
minishift addon apply anyuid

After the start?

**Comment by ravichalla** [comment]
> Are you running this:
> 
> minishift ssh -- sudo setenforce 0
> 
> # Openshift console bug. anyuid needs to be applied after startup
> minishift addon apply anyuid
> 
> After the start?

**Comment by ravichalla** [comment]
What actually , it does . I haven't executed it after start.

**Comment by lordofthejars** [comment]
You need to execute after start.
