### ISSUE TITLE
Validation with https://git.io/_has fails on Mac OS

### ISSUE THREAD

**Issue by koziolk** [redhat-developer-demos/istio-tutorial#224]
While executing the following command on Mac OS (Mojave 10.14.4):

`curl -sL https://git.io/_has | HAS_ALLOW_UNSAFE=y bash -s` 

I'm getting:

```
has v1.4.0
USAGE:	 has <command-names>..
EXAMPLE: has git curl node
```

Instead of a list of installed CLI tools.

**Comment by muhammadnasr** [comment]
same with me

**Comment by lordofthejars** [comment]
If you run from the root directory it works.
