### ISSUE TITLE
there is no minishift 3.11.0 anymore

### ISSUE THREAD

**Issue by bmachado** [redhat-developer-demos/istio-tutorial#229]
─▪ minishift start
-- Starting profile 'istio-tutorial-1-1-1'
-- Downloading OpenShift Container Platform client binary 'oc'
Error starting the cluster: Error attempting to download and cache oc: https://mirror.openshift.com/pub/openshift-v3/clients/3.11.0/macosx/oc.tar.gz url is inaccessible

---
I'm using "minishift config set openshift-version v3.11.43" instead

**Comment by lordofthejars** [comment]
We are in the process of migrating to Minikube, so the setup section is going to be replaced to only require kubectl and not oc.
