### ISSUE TITLE
istio_request_* metrics not found in Prometheus/Grafana

### ISSUE THREAD

**Issue by lucasponce** [redhat-developer-demos/istio-tutorial#23]
Hi,
Following the steps of the tutorial, installing all components and having succesfully the services
i.e.
```
[lponce@attilan ~]$ curl $(minishift openshift service customer --url)
C100 * {"P1":"Red", "P2":"Big"} && Clifford v1 2448987483-w9vv4 2 *
```
I can't get the istio_request_* metrics in p8s/grafana, so some high level info is missing.

![image](https://user-images.githubusercontent.com/1662329/35690676-c2280a44-0776-11e8-9a27-b9ad1829c0a3.png)

Is this anything people have seen before ? any workaround avaiable ?
Thanks

**Comment by lucasponce** [comment]
This issue seems related to
https://github.com/istio/issues/issues/168

**Comment by rafabene** [comment]
This seems to be fixed.

<img width="496" alt="screenshot 2018-02-28 09 07 29" src="https://user-images.githubusercontent.com/30131/36791863-e481aff0-1c66-11e8-8e81-0ddd0ede8322.png">
