### ISSUE TITLE
spring boot code is broken

### ISSUE THREAD

**Issue by muhammadnasr** [redhat-developer-demos/istio-tutorial#236]
service customer/java/springboot code will not work as it does not implement health check 
only quarkus code works

**Comment by cricket007** [comment]
Related to #141?

**Comment by lordofthejars** [comment]
Working in that today.

**Comment by lordofthejars** [comment]
Fixed, now there is a `Deployment_jvm.yml` files that can be used to deploy Spring Boot and JVM services in general for the tutorial. Now I am going to update docs.
