### ISSUE TITLE
Error installing preferences service

### ISSUE THREAD

**Issue by lucasponce** [redhat-developer-demos/istio-tutorial#24]
Following the steps, from a clean environment, preferences pods got in a error loop.
Details can be found here:
https://gist.github.com/lucasponce/28acb79f6f10fbefce32c9a0e53a8294

**Comment by xeviknal** [comment]
Which istio version are you using? 0.4.0?
I had problems installing preferences services before, but it was problem of image registry.
Also, I used istio 0.5.0 but had lots of troubles on installation and came back to 0.4 version.
Last and a little bit mean, I found myself running all the command of the tutorial really fast (bulk mode) and I realized that stopping among commands helps to better installation. Can't explain why accurately.

**Comment by rafabene** [comment]
It seems that you not build the prerence image using minishift docker daemon: eval $(minishift docker-env). Please re-open if you still facing the issue.
