### ISSUE TITLE
pod name is no longer accurate

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/istio-tutorial#253]
The quarkus native version of recommendation does not report the correct Pod name
https://www.screencast.com/t/DQPcxIIm

The from 'f11b097f1dd0' should be the pod name "recommendation-v1-58f5bb6bfd-hhh8c" or a substring thereof

**Comment by lordofthejars** [comment]
it is really weird, fixing to full version and see

**Comment by lordofthejars** [comment]
Funny I know why this is happening, it is because of GraalVM compilation. I am going to see if it can be fixed.
