### ISSUE TITLE
Use istioctl instead of oc or kubectl

### ISSUE THREAD

**Issue by christian-posta** [redhat-developer-demos/istio-tutorial#28]
istioctl does validation of resource files; `oc` and `kubectl` do not. It's preferable to use `istioctl` for creating and replacing istio resource files.

**Comment by rafabene** [comment]
Now that we presented this Workshop at DevNexus, should we merge this change?

**Comment by christian-posta** [comment]
I see someone did make the change in some places... should update it in all places. I can rescind my PR since it's out of date... again... we need a way to have multiple PRs in flight without generating conflicts because we're all working on the same, single Readme.md.
