### ISSUE TITLE
Istio features Summit MVP

### ISSUE THREAD

**Issue by kameshsampath** [redhat-developer-demos/istio-tutorial#30]
the following are the Istio that will be for Summit MVP:

[] Router Rule
[] Mutual TLS
[] Destination Policies
[] A/B Testing ( this closely resembles our Smart canaries)

@burrsutter @DonSchenck @rafabene @yanaga  - we need to add the missing pieces to the tutorials and push the other ones to lower priority

**Comment by burrsutter** [comment]
Is it A/B Testing or the A/B Deployment?  
A good description of A/B Testing - https://www.optimizely.com/optimization-glossary/ab-testing/
looking for better business outcomes.

**Comment by yanaga** [comment]
AFAIK the only people that use "A/B Deployment" are the OpenShift guys. Everyone else uses "A/B Testing", but we're just showing the route part. Without metrics, many people will argue that we can't call it "A/B Testing".

**Comment by burrsutter** [comment]
Lets close this issue as it is not actionable.
