### ISSUE TITLE
Rate limits is not working

### ISSUE THREAD

**Issue by rafabene** [redhat-developer-demos/istio-tutorial#31]
I've applied the files and even so I was not able to get any error.

**Comment by DonSchenck** [comment]
I'm working on this; I'm not able to assign myself.

**Comment by rafabene** [comment]
FYI: it works on Bookinfo on OpenShift: https://learn.openshift.com/middleware/resilient-apps/

**Comment by jamesfalkner** [comment]
See https://github.com/istio/issues/issues/257 and associated PR https://github.com/istio/istio/pull/4576

Adding a `namespace` qualifier to the `QuotaSpecBinding` makes it work (we're using this for the istio summit lab).
