### ISSUE TITLE
Correct the duplication of customer and preference in tracing

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/istio-tutorial#33]
https://screencast.com/t/5CTFcHr9r7p

**Comment by rafabene** [comment]
That is expect since customer and preference creates two spans ( https://jaeger.readthedocs.io/en/latest/architecture/#span ) = Inbound/Outbound

**Comment by rafabene** [comment]
This is not duplicate. Note that the first preference (inbound) shows the http.url=http://preference:8080/ and upstream_cluster=in.8080. The second span (outbound) of preference shows http.url=http://recommendation:8080/ and upstream_cluster=out.recommendation.tutorial.svc.cluster.local\|http

<img width="819" alt="screenshot 2018-02-27 13 04 12" src="https://user-images.githubusercontent.com/30131/36745929-0daf480e-1bbf-11e8-8948-4cfbe46adea0.png">
<img width="916" alt="screenshot 2018-02-27 13 04 23" src="https://user-images.githubusercontent.com/30131/36745931-0dc78036-1bbf-11e8-9292-cbf2e3d4c366.png">

**Comment by burrsutter** [comment]
So the secret here is "upstream_cluster" and "in." and "out."

**Comment by rafabene** [comment]
the http.url is also relevant.
