### ISSUE TITLE
Can Sleuth address the tracing headers better?

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/istio-tutorial#35]
https://github.com/redhat-developer-demos/istio-tutorial/blob/master/customer/src/main/java/com/redhat/developer/demos/customer/tracing/HttpHeaderForwarderHandlerInterceptor.java#L22

**Comment by rafabene** [comment]
Doesn't this conflicts with #15 and/or #21 ?

**Comment by pavolloffay** [comment]
Yes it conflicts with #21. 

Sleuth clould be also used to propagate the headers.

**Comment by rafabene** [comment]
Since it conflicts, I'll close this issue.
