### ISSUE TITLE
pods don't start, stuck in ImagePullBackOff and ErrImagePull

### ISSUE THREAD

**Issue by abonas** [redhat-developer-demos/istio-tutorial#37]
when working in minishift, following the tutorial, all steps completed successfully, but oc get pods -w show that pods are not starting
```
NAME                       READY     STATUS         RESTARTS   AGE
customer-727474719-z4kcx   1/2       ErrImagePull   0          1h
NAME                       READY     STATUS             RESTARTS   AGE
customer-727474719-z4kcx   1/2       ImagePullBackOff   0          1h
```

`oc describe pod` ... shows:
"Failed to pull image "example/customer:latest": rpc error: code = 2 desc = Error: image example/customer:latest not found"
not sure where it should be looking for the image, I'm running this from the istio-tutorial/customer folder

**Comment by rafabene** [comment]
It seems that you not build the prerence image using minishift docker daemon: eval $(minishift docker-env). Please re-open if you still facing the issue.

**Comment by abonas** [comment]
@rafabene I followed the instructions again.
Now this is where it is stuck:
[abonas@abonasredhat customer (master)]$ oc create -f src/main/kubernetes/Service.yml -n tutorial
Error from server (AlreadyExists): error when creating "src/main/kubernetes/Service.yml": services "customer" already exists
[abonas@abonasredhat customer (master)]$ oc expose service customer
error: services "customer" not found

**Comment by rafabene** [comment]
Try oc expose service customer -n tutorial, you might be using a different namespace/project. Check it with `oc get project`

**Comment by abonas** [comment]
`oc get project`
NAME              DISPLAY NAME   STATUS
default                          Active
istio-system                     Active
kube-public                      Active
kube-system                      Active
myproject         My Project     Active
openshift                        Active
openshift-infra                  Active
openshift-node                   Active
tutorial                         Active

`oc expose service customer -n tutorial`
Error from server (AlreadyExists): routes "customer" already exists

`oc get route
`
NAME            HOST/PORT                                          PATH      SERVICES        PORT         TERMINATION   WILDCARD
grafana         grafana-istio-system.192.168.39.146.nip.io                   grafana         http                       None
istio-ingress   istio-ingress-istio-system.192.168.39.146.nip.io             istio-ingress   http                       None
jaeger-query    jaeger-query-istio-system.192.168.39.146.nip.io              jaeger-query    query-http   edge/Allow    None
prometheus      prometheus-istio-system.192.168.39.146.nip.io                prometheus      prometheus                 None
servicegraph    servicegraph-istio-system.192.168.39.146.nip.io              servicegraph    http                       None

**Comment by rafabene** [comment]
Sorry. instead of `oc get project`, the command that shows your current namespace/project is `oc project`. To change to the right project/namespace, use `oc project tutorial`. CAn you try and give me an update? Thanks.

**Comment by abonas** [comment]
switching projects somehow logs out of minishift.
I found this [issue](https://github.com/minishift/minishift/issues/1966) reported.
and I still get a problem to proceed because when I relogin the error remains.
