### ISSUE TITLE
Explain why egresshttpbin and egressgithub doesn't work

### ISSUE THREAD

**Issue by rafabene** [redhat-developer-demos/istio-tutorial#40]
When I look at the original code of these projects I don't understand why they fail. It's also not clear in the readme file why they fail and why they need an egress rule.

**Comment by burrsutter** [comment]
Unlike raw Kubernetes, Istio/Envoy block all outbound traffic from a pod (envoy intercepts all in/out traffic) as that is considered to be better/smarter for security reasons.  One of the more interesting attack vectors (if you are a blackhat hacker) is to install a small process on a remote server, have it collect interesting data and "phone home".   So, Istio/Envoy block that outbound traffic (pod to outside the service mesh).    Therefore, you must explicitly open up the egress routes, kind of like opening up ports in the firewall.

**Comment by christian-posta** [comment]
I recommend we close this. Egress works differently in Istio 0.8 anyway.

**Comment by rafabene** [comment]
And also because we will rewrite the Egress application.
