### ISSUE TITLE
Is anyone else facing issues installing Minishift 1.13.0 on their Mac?

### ISSUE THREAD

**Issue by indrayam** [redhat-developer-demos/istio-tutorial#42]
Already opened an issue with Minishift:
https://github.com/minishift/minishift/issues/2026

Thought I would check if anyone else had similar issues. I would really like to get on with the tutorial, but it’s hard if you cannot get past the very first step..:-(

**Comment by rafabene** [comment]
Since this seems to be a bug on minishift and this tutorial uses minishift 1.12 ( https://github.com/redhat-developer-demos/istio-tutorial#setup-minishift ) , I'm closing this issue.
