### ISSUE TITLE
Why are we using VirtualBox for minishift?

### ISSUE THREAD

**Issue by christian-posta** [redhat-developer-demos/istio-tutorial#47]
If people are downloading docker for mac, why aren't we using xhyve to boot minishift on mac (isn't that the default anyway?)

**Comment by rafabene** [comment]
+1 to remove VirtualBox dependency

**Comment by burrsutter** [comment]
We want the Bash commands to work for Linux as well.  VirtualBox also has a nice UI which allows you to recover from a VM that minishift has lost track of.

**Comment by rafabene** [comment]
So let's close this issue. Someone who doesn't want Virtualbox can skip that line.
