### ISSUE TITLE
servicegraph responses 404

### ISSUE THREAD

**Issue by john-deng** [redhat-developer-demos/istio-tutorial#54]
Hi, I tried this tutorial, it worked very well except servicegraph which return 404

open http://servicegraph-istio-system.10.0.75.2.nip.io/ in browser

404 page not found

here is the service log:

```
2018/02/23 08:01:46 Starting servicegraph service at :8088
```

**Comment by rafabene** [comment]
Try http://servicegraph-istio-system.10.0.75.2.nip.io/dotviz
