### ISSUE TITLE
OpenTracing doesn't propagate user-agent header

### ISSUE THREAD

**Issue by rafabene** [redhat-developer-demos/istio-tutorial#60]
Since we merged #57 the use case https://github.com/redhat-developer-demos/istio-tutorial#smart-routing-based-on-user-agent-header-canary-deployment doesn't work anymore since the user-agent header is not being propagated.

@pavolloffay Can you handle this?

**Comment by rafabene** [comment]
Fixed by reverting https://github.com/redhat-developer-demos/istio-tutorial/commit/387acf756e6bcf582ea4d1543e8ab05f37f89f27

**Comment by pavolloffay** [comment]
The problem is that B3 propagation does not support baggage. 

@rafabene there are two solutions. Revert commit in https://github.com/redhat-developer-demos/istio-tutorial/pull/57. Or use the same approach as before to propagate `user-agent`

**Comment by rafabene** [comment]
I've just reverted.
