### ISSUE TITLE
Is recommendation_requestcount.yml still up to date?

### ISSUE THREAD

**Issue by metacosm** [redhat-developer-demos/istio-tutorial#73]
https://github.com/redhat-developer-demos/istio-tutorial/blob/master/istiofiles/recommendation_requestcount.yml. I think that several fields should be renamed from snake case to to camel case e.g. `instance_name` -> `instanceName`…

**Comment by rafabene** [comment]
@lordofthejars @kameshsampath Do you know the answer?

**Comment by kameshsampath** [comment]
@rafabene - I have not tried that yet, let me know if you want me to take a shot at it?

**Comment by lordofthejars** [comment]
@rafabene I think it worked because if not I would have written down in the document.

**Comment by metacosm** [comment]
Actually, I got the answer since, the go parser in Istio is lenient and accepts both cases so it works but the reference says that camel case should be used… though it's not even internally coherent (description with camel case, example with snake case, at least last time I checked). :(
