### ISSUE TITLE
Prometheus Operator directions?

### ISSUE THREAD

**Issue by StevenACoffman** [redhat-developer-demos/istio-tutorial#76]
Instead of the prometheus istio addon directory, can you provide an example for the prometheus Operator? This is more standard RedHat OpenShift way going forward.

**Comment by christian-posta** [comment]
Happy to have PR for what you'd like to see @StevenACoffman 

Right now, the installation of Istio and its components is really just for "demo purposes" with the aim to get users familiar with the Istio API.

**Comment by rafabene** [comment]
Prometheus is part of Istio 1.1.x. This issues doesn't make sense anymore.

**Comment by StevenACoffman** [comment]
Istio helm chart installs Prometheus, and so does the Prometheus operator, but each Prometheus has a different configuration. It would be better if a single Prometheus operator could be installed and add additional scrape configs for istio.
