### ISSUE TITLE
Adding Right Namespace to Istio Configurations

### ISSUE THREAD

**Issue by kameshsampath** [redhat-developer-demos/istio-tutorial#8]
While working on #6 I found that there are many resources in the tutorial that were not prefixed with right namespace - as with the current tutorial it should be **springistio**. We need to update the Istio Configuration  for the same else there will be weird behaviours.

**Comment by burrsutter** [comment]
I would like to change from "springistio" to something more generic, any recommendations on a different string?

**Comment by rafabene** [comment]
Not relavant anymore
