### ISSUE TITLE
PLACEHOLDER for 0.8 update

### ISSUE THREAD

**Issue by christian-posta** [redhat-developer-demos/istio-tutorial#82]
We are expecting a PR from @lordofthejars for the update to Istio 0.8 and more specifically to the v1alpha3 configurations.

Work is being done here: https://github.com/lordofthejars/istio-tutorial/tree/istio-0.8.0

I'm opening this issue to capture notes and feedback about the migration to the new APIs. I expect this list to just move to the PR when it gets open. Here's what I have so far:

notes:

- [X] istio.yaml changed to istio-demo.yaml for installation
- [x] we don't need to install jaeger separately, it gets installed automatically now in "istio-tracing"
- [x] The listing of istio components when first installed is wrong/not updated for 0.8? (Alex)
- [x] Need to update the section on tracing
- [X] update the output of istioctl version
- [x] need to explicity inject proxyv2! ISTIO_PROXY_IMAGE=proxyv2
- [x] Either make note about the 10s delay of the rds or add a line to shorten it to 1s 
    _I have not been able to reduce the rds time (opened question at https://groups.google.com/forum/#!topic/istio-users/DxwAJRBbLGU) it seems a bug.
- [ ] Should add a section on "eventual configuration convergence"
- [x] Get rid of old route rules files\
- [x] rename route rules to get rid of "route rule".. should just be "recommendation-service...." (Alex)
- [x] rename the Istio files mapping to the concepts e.g. routerule as `virtual-service`
- [ ] how do we handle precedence, though its not part of the tutorial but then would love for the creators to understand it well and handle it as needed
- [x] having "DestinationRule" for each service as seperate file rather then having them repeat in each and every "VirtualService" now (Alex)
- [ ] add `.editorconfig` file for uniform and easier formatting of yaml and java files
- [ ] docker file rebuilds for `JAGER` endpoints when using `istio-tracing`
- [x] Update tips and tricks section (Alex)

more to come... /cc @rafabene

**Comment by kameshsampath** [comment]
an example of `.editorconfig`
----

```root = true

[*]
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = false
insert_final_newline = false

[*{.java,.js}]
indent_style = space
indent_size = 4
end_of_line = lf
insert_final_newline = true

[*{.yaml,.yml,.json}]
indent_style = space
indent_size = 2
end_of_line = lf```

**Comment by kameshsampath** [comment]
when i was refreshing myself with latest Istio Jargons I saw  error while doing this task : https://github.com/kameshsampath/istio_tutorial#smart-routing-based-on-user-agent-header-canary-deployment

When we go as per the steps deployment of `istiofiles/route-rule-recommendation-v1.yml` and ` istiofiles/route-rule-safari-recommendation-v2.yml` is causing some conflicts in istio-pilot which was throwing the following error in the log 

```
customer-5dffb8bff9-rq9sl istio-proxy [2018-06-14 12:10:47.058][18][warning][config] bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener 0.0.0.0_80: Only unique values for domains are permitted. Duplicate entry of domain recommendation.tutorial.svc.cluster.local
```
and my routes did not work , the following VirtualService which is same as @lordofthejars migration files, fixed the issue and just deploying this alone is good for the task.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: recommendation-safari
spec:
  hosts:
   - recommendation
  http:
  - match:
    - headers:
        user-agent:
          regex: ".*Safari.*"  
    route:
    - destination:
        host: recommendation
        subset: v2
  - route:
    - destination:
        host: recommendation
        subset: v1
```

I thought to call this out as we might need to take care of these scenarios in the migration of the tutorial and remove all redundant rules

**Comment by lordofthejars** [comment]
But you still a DestiantionRule defining the subset

**Comment by kameshsampath** [comment]
no i just have one global destination rule and never changed it.  in way I find it easier for maintenance rather having `DestinationRule` in each and every `VirtualService`

**Comment by lordofthejars** [comment]
Ok, my latest commit just finishes the migration. There is the 503-retry example that I have not been able to make it work.

So, if you don't mind, I send the PR so you can start reviewing it and meanwhile improving with all remaining tasks

**Comment by christian-posta** [comment]
I have it working @lordofthejars 
thx for the PR, will look through it

**Comment by christian-posta** [comment]
@kameshsampath yah.. we will want to remove all traces of the old v1alpha1 configs. Istio will not support those going forward so no need to keep them around.

**Comment by lordofthejars** [comment]
@christian-posta I am going to fix minor things like correcting the "The listing of istio components when first installed is wrong/not updated for 0.8?" and "Either make note about the 10s delay of the rds or add a line to shorten it to 1s"

**Comment by christian-posta** [comment]
closing this as 0.8 has been merged.
