### ISSUE TITLE
Update Diffy use case

### ISSUE THREAD

**Issue by lordofthejars** [redhat-developer-demos/istio-tutorial#91]
Update Diffy use case to Istio 0.8. Maybe we can even update to Diferencia 0.2(https://lordofthejars.github.io/diferencia-docs-site) instead of Diffy.

**Comment by lordofthejars** [comment]
@rafabene @christian-posta In fact when this is updated, I will send a PR changing Diffy to Diferencia :)

**Comment by rafabene** [comment]
Merged
